### PR TITLE
Enhanced Partner image/logo styles on landing page #173

### PR DESCRIPTION
**Pull request by trblackw**
## Motivation and Context

Attempts to remedy issue #173 
## How Has This Been Tested?

No changes in logic made
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [√ ] feature enhancement

## Checklist:

- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Paarmita** [comment]
@trblackw Thanks for the PR! Can you please add the same property for Contributors as well.

**Comment by trblackw** [comment]
Note that I also added hover effects to the team cards for issue #169

**Comment by Paarmita** [comment]
@trblackw On hover the team cards the image size should reduce and the social icons must also be there. Can you add these changes as well? :)

**Comment by trblackw** [comment]
Yes but I won’t be able to until probably tomorrow

**Pull request merged**
