### PR TITLE
Added proper URL's for Footer

### PR DESCRIPTION
**Pull request by nirmalks**
* Added URL's for partners and about us links
* Replace anchor tags with link and HashLink to avoid page refresh
* Modified links to homepage with leading slash

Fix links to proper URL's and replaced anchor tags with Link and HashLink in footer 

## Description

* Added URL's for partners and about us links
* Replace anchor tags with link and HashLink to avoid page refresh
* Modified links to homepage with leading slash

## Motivation and Context

https://github.com/Ignitus/Ignitus-Client-Side-Development/issues/50

## How Has This Been Tested?

Checked the links from homepage and about us page.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@nirmalks you also need to change the URL of the Partners and I guess you also forgot to change the About us URL as well, kindly look into this 👍

**Comment by nirmalks** [comment]
> @nirmalks you also need to change the URL of the Partners and I guess you also forgot to change the About us URL as well, kindly look into this

I have linked the "partners" link to the div in the homepage(Supporters and Partners content) and "aboutus" to the separate page as used in the top navigation. Should they point to different URL's?

**Comment by Paarmita** [comment]
@nirmalks Yes, they point to basic home URL. Please change the URL for them as well.

**Comment by nirmalks** [comment]
@Paarmita Sorry, I still dont get it. which link should be changed? 
1. Should "partners" link point to home URL("#") as it was previously linked to?
2. Is the "aboutus" URL ok?
3. >Please change the URL for them as well.

Does it refer to other links refer to links like "internship" to be pointed to home URL?

**Pull request merged**
