### PR TITLE
sign up component added

### PR DESCRIPTION
**Pull request by afreen23**
## Description
The sign up page for the user with responsiveness

## Screenshots (if appropriate):
[Screenshot](https://screenshots.firefox.com/tw6HR4SmV5nf8nyy/localhost)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-  [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Paarmita** [comment]
@afreen23 it's not looking good in mobile view. Can u look into this.

**Comment by afreen23** [comment]
@Paarmita  okay!

**Comment by afreen23** [comment]
@Paarmita  check now! I fixed it!

**Comment by Paarmita** [comment]
@afreen23 Thanks :+1:

**Pull request merged**
