### PR TITLE
Implement the Contributor and Partner UI

### PR DESCRIPTION
**Pull request by paperlambda**
## Description
I changed the UI for the new one according the UI Toolkit provided. I simply added `.card` component to wrap the images and added utility classes for shadowing, sizing, etc.

## Motivation and Context
This solves #33  as of updating the appearance of the web

## How Has This Been Tested?
No, i have not. The affected area should not be considered since the structure of the components is isolated for itself.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@paperlambda can you please resolve merge conflicts 👍

**Comment by sidbentifraouine** [comment]
Seems good to me, just add a space after your class name and it's ok `.myclass {...}` 🙂

**Comment by paperlambda** [comment]
@sidbentifraouine i'm pushing the fixes. anyway, would like to consider using prettier for code formatting? so you dont have to worry about code formatting anymore 💡

**Comment by divyanshu-rawat** [comment]
Thanks @paperlambda 👍

**Pull request merged**
