### PR TITLE
Add filter to contributors to avoid repetition

### LINKED ISSUE #301: Add filter for repeated usernames in Contributor's section
**Describe the bug**
On the contributor's section, as contributors from 2 different repositories(Client and server) are rendered so there are some overlapping Github usernames.

**To Reproduce**
See profiles in this section

Screenshot 2019-04-22 at 9 08 34 PM

**Expected behavior**
We can add a filter to remove the repeated usernames.

### PR DESCRIPTION
**Pull request by arc9693**
Fixes #301

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by arc9693** [comment]
@divyanshu-rawat  Please review.

**Comment by CDharmateja** [comment]
@arc9693 The duplicates aren't showing but the indexedDB on the client side still stores the duplicates. So I think it better to remove duplicates in the ignitus-Api folder right after fetching and before putting in the database. Also I was thinking, the list order is according to the number of contributions they've made. So if someone made contributions to both front-end and back-end, then adding up both and showing them according to the contributions would be better. Also there are errors Travis CI, try solving them.

**Comment by arc9693** [comment]
@CDharmateja Yes. Acknowledged what you are saying.

**Comment by arc9693** [comment]
@Paarmita  @divyanshu-rawat  I have updated my PR as required.  Also, I updated package-lock.json as the Travis file wasn't running at all earlier. One of the tests is still failing, but it is not because of the changes i introduced.

**Pull request merged**
