### PR TITLE
Update Vulnerable Packages, Fix Routing back to Home Page, Fix Typos

### PR DESCRIPTION
**Pull request by ATLowther**
## Description

Upon first cloning the repo, I received npm security warnings. I immediately updated those packages.

The Sign Up drop-down menu in the navigation was going off the right side of the screen, so I changed the alignment with a bootstrap class

Once you navigated away from the home page, the links back to the home page or relative links therein were broken. The links back to the home page could be fixed with a <Link to="/">, but it seems there is a bug with react-router that doesn't properly support anchor tags, so in order for something like <Link to="/#what-we-do">, I installed another dependency that resolves this issue and changes the previous statement to something like  <HashLink to="/#what-we-do">

There were some typos on the About Us page that I noticed, so I fixed those.

## Motivation and Context

It solves potential security issues; The routing is now fixed, which previously required somebody to refresh the home page in order to return to it; some typos make the site look cleaner/more professional.

#18; Although, I am surprised this issue had no been closed. Anchor tags had already been implemented when I forked the repo, they just didn't work properly once navigating away from the home page.

## How Has This Been Tested?

I npm start locally and tested the links

Safario Browser. I clicked the links with my mouse.

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project. - **I did not see any Linter provided for this project, I am not sure the desired code style.**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@ATLowther  Thanks for the PR 👍 .
@Paarmita will review it :)

**Comment by Paarmita** [comment]
@ATLowther THe PR looks food. But we have more stylish and graceful UI design worked by our design team which needs to be implemented. So we need to refactor the code with the new UI.

**Comment by ATLowther** [comment]
@Paarmita Where is the new UI. Is it available from the Master branch?

**Comment by divyanshu-rawat** [comment]
@ATLowther from which branch have you created your branch? is it from master? as your PR is reflecting commits of other developers as well.

Apart from that here is the link to the new UI - https://github.com/Ignitus/Ignitus-UI-Kit/blob/master/Ignitus.png

**Comment by ATLowther** [comment]
@divyanshu-rawat I grabbed the existing develop branch...Should the branches be getting deleted as they are merged?

**Comment by divyanshu-rawat** [comment]
We are not deleting the branch, after merging but there is something wrong with the pr that you sent ,as it shows +3,014 −2,457  additions and deletions, kindly create a branch from master.

**Comment by ATLowther** [comment]
@divyanshu-rawat @Paarmita: It has been updated, based on the most recent master branch.

**Comment by Paarmita** [comment]
@ATLowther Can u please share screenshots of the changes you made?

**Pull request merged**
