### PR TITLE
feat: Caching API Calls using indexedDB

### LINKED ISSUE #209: Caching Github Api Calls
**Is your feature request related to a problem? Please describe.**
Even if a new contributor is not added to the project, everytime when we move to `http://www.ignitus.org/aboutus` an api call is made to the `github server` in turn exhausting number of api calls allowed in an hour.

**Describe the solution you'd like**
No consumption of api calls until a new contributor is added, in summary if no new contributor is added to the project then it will keep on returning existing contributors from the `cache` instead of making an api call to fetch the contributors.

**Describe alternatives you've considered**
None till so far.

**Additional context**
Helpful: 

- https://stackoverflow.com/questions/14886664/caching-github-api-calls
- Headers like `(ETag, Last-modified, Cache-control)` will help.
- https://developer.github.com/v3/#conditional-requests

`Most responses return an ETag header. Many responses also return a Last-Modified header. You can use the values of these headers to make subsequent requests to those resources using the If-None-Match and If-Modified-Since headers, respectively. If the resource has not changed, the server will return a 304 Not Modified.`

### PR DESCRIPTION
**Pull request by CDharmateja**
Caches API Calls using indexedDB

## Description

The API calls for github and testimonials are cached and stored in indexedDB. The data is retrieved using network first strategy. For GitHub API calls, if data is not modified then data from indexedDB is retrieved else fetched from network. 

## Motivation and Context

fixes #209 

## How Has This Been Tested?

The json response along with ETag header from API is stored in indexedDB which is verified by checking it `indexedDB` in chrome dev tools in application tab. When loading the page again, the data is retrieved from indexedDB which is tested by `console.log` in code.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@CDharmateja merge request is in DRAFT are you still working on this? let me know then @Paarmita won't merge it until you are done with the functionality. 👍

**Comment by CDharmateja** [comment]
@divyanshu-rawat  I have put the pull request in draft mode because of using ETag for the testimonials too. Since the header for it needs to be added in server side, either we can wait for it and add its functionality or make another PR for it. Anything is fine for me. I have removed PR from draft.

**Comment by divyanshu-rawat** [comment]
@CDharmateja do we have an header for it server-side as well?, as I think it's caching is working fine on client side.

As per the response from sever-side we are receiving 304 not modified.
```
Request URL: https://api.github.com/repos/Ignitus/Ignitus-Client-Side-Development/contributors
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 140.82.113.6:443
Referrer Policy: no-referrer-when-downgrade

```

**Comment by CDharmateja** [comment]
Yeah it has `ETag` and `Last-Modified` headers which browser uses for caching. But the advantage with indexedDB is that using it with service worker we can display stored result even when user is offline.

**Pull request merged**
