### PR TITLE
Made some of desired changes for the issue #19

### PR DESCRIPTION
**Pull request by amitmangotra**
Resolved the Testimonial and Card image problem for mobile view and
provided padding on sides for the same. Need to make changes (align in center for mobile view) for
contributor list and Supporters&Partners.

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@amitmangotra , @Paarmita will review the changes and then merge it 👍

**Comment by Paarmita** [comment]
@amitmangotra Contributors and Partners images also need to be aligned.

**Comment by amitmangotra** [comment]
@Paarmita Yes, I am working on it.

**Comment by amitmangotra** [comment]
@Paarmita I just finished aligning the contributors and partners images for mobile view. Please review it and let me know if anything more is required.

**Comment by Paarmita** [comment]
@amitmangotra Looks good to me :)

**Comment by divyanshu-rawat** [comment]
Thanks @amitmangotra 👍

**Pull request merged**
