### PR TITLE
WIP(#114): wrote a push handling routing and added envs in linter

### LINKED ISSUE #114: Integrating Push Notifications
Integrating Push Notifications 

Please go through A walk through of integrating the Push API through the use of Service Workers into your Node.js back end and your React.js front end before integrating it.

Web push notification are one of the many features at the heart of giving Progressive Web Apps a truly competitive experience to their Native App counterparts. 

Please see the attached medium publication to know more about it - https://medium.com/@jasminejacquelin/integrating-push-notifications-in-your-node-react-web-app-4e8d8190a52c

Link to rest-api NODE.JS backend - https://github.com/Ignitus/Ignitus-rest-api

Gôôd Luck 👍

### PR DESCRIPTION
**Pull request by sidbentifraouine**
# Context
This PR should close #114 so

## Description
I extended the behavior of the current SW and added some linting env in order to let the client receive push notifications. See below for the demo.

## Demo

sw

## Types of changes
- [x] New feature: push notifications

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

I'll need to do a PR on the backend side of this issue, have I to updated the doc right now or you need to test it first ?

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@sidbentifraouine I tried testing it but I am not been able to see the intended behaviour.
this is what I am recieving as json.


```
{
websocket: true,
origins: [
"*:*"
],
cookie_needed: false,
entropy: 3800824125
}
```

**Comment by sidbentifraouine** [comment]
@divyanshu-rawat 
Hi I'll create a pull request to make this work, but for now I'm not able to make the extension of the SW work on dev server.
I'm doing it this following way:
`npm run build && npm serve` 😊

**Comment by sidbentifraouine** [comment]
@divyanshu-rawat 
Have you tried 
```
npm run build && npm serve
```
It seems that the sw precache doesn't include my imported push handler...

**Comment by divyanshu-rawat** [comment]
@sidbentifraouine Now I have tried using ``` npm run build && npm serve ```.
I am getting this err.

I am also curious about this thing.

``` const publicUrl = new URL(process.env.PUBLIC_URL, window.location); ```
what ``` process.env.PUBLIC_URL ``` here refers to?

screen shot 2018-10-19 at 7 24 23 pm

**Comment by divyanshu-rawat** [comment]
@sidbentifraouine I have added localhost:500 to content settings in chrome, so it's not showing any err as of now, everything is working fine but I am not been able to see the dialog box like one in your gif having a text ``` hello from backend ```

I am getting this on the console now but no dialog.

screen shot 2018-10-19 at 8 04 25 pm

**Comment by sidbentifraouine** [comment]
@divyanshu-rawat  Awesome 😁
You're welcome !

**Comment by divyanshu-rawat** [comment]
@sidbentifraouine can you debug an issue as everything is working fine locally, but at www.ignitus.org I am not been able to see notification or even a network request to the endpoint www.ignitusrestapi/subscribe

**Comment by divyanshu-rawat** [comment]
@sidbentifraouine that's the concern with ``` npm start ``` and ``` npm run build && npm serve ```
so, can you solve this.
In production I think it's not doing  ``` npm serve  ```

**Comment by sidbentifraouine** [comment]
@divyanshu-rawat OFC, I'll do my best 🙂

**Comment by divyanshu-rawat** [comment]
@sidbentifraouine We are using heroku for production not docker. maybe I guess we can create Procfile to solve this.
I tried this as well but it's not working https://stackoverflow.com/questions/47898402/push-notification-in-create-react-app-web

**Comment by sidbentifraouine** [comment]
The thing is that: SWPrecache imports the script after the build, I'll have to figure out how to make it do that event in dev-server 🤔

**Comment by divyanshu-rawat** [comment]
Please find build log for Heroku, it may come handy.
screen shot 2018-10-20 at 1 23 58 am

**Comment by sidbentifraouine** [comment]
@divyanshu-rawat 
I don't know how it works but can you make heroku serve the static, or you can just run a `npm start` command? If so we can write an express tiny app that will serve it for us

**Pull request merged**
