### PR TITLE
Get Navigation and Footer component out

### PR DESCRIPTION
**Pull request by meyfleur**
#71

Description

revert previous commit
move Navigation and Footer to App.js and remove it from all other components

### CODE REVIEW

**Comment by divyanshu-rawat** [comment]
@meyfleur it still has merge conflicts, kindly have a look 👍

**Comment by outsourcegb** [comment]
👍

**Comment by divyanshu-rawat** [comment]
@meyfleur can you please look into the conflict? and update the PR accordingly.

**Comment by meyfleur** [comment]
done, pls merge if ready

**Pull request merged**
